### ISSUE TITLE
【This Patch not matching in currently OC code? 】

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [talamortis/OregonCore-Modules#28]
https://github.com/talamortis/OregonCore-Modules/blob/60164310d1bb4904a2225255aca95670d5cd0b8f/patches/2020-10-21-duel-spec-OregonCore.patch#L4

Steps : 
1>Put this Patch files in OC core files .
2>Git bash command : git apply --stat 2020-10-21-duel-spec-OregonCore.patch [to read this patch status ]
showed : 
[<a href="https://sm.ms/image/b2wr6Em4zOunNCP" target="_blank"><img src="https://s2.loli.net/2022/04/27/b2wr6Em4zOunNCP.png" /></a>](url)

3>Git bash command : git apply --check 2020-10-21-duel-spec-OregonCore.patch [to check this patch status before install ]
showed : 
[<a href="https://sm.ms/image/8vguHn1OrBcEw7Y" target="_blank"><img src="https://s2.loli.net/2022/04/27/8vguHn1OrBcEw7Y.png" /></a>](url)

4>can not directly to merge.

**Comment by talamortis** [comment]
alot has changed since this patch. this will prob need some rework or be turned into a module :)

**Comment by yuyu-lovegelin111333** [comment]
> alot has changed since this patch. this will prob need some rework or be turned into a module :)

Understood and thnaks , also hope this duel-spec function can be turned into a module , in future , that' ll be a very perfect one .
