### ISSUE TITLE
CrossfactionBG module not loading.

### ISSUE THREAD

**Issue by d3athbl0w** [talamortis/OregonCore-Modules#8]
**Describe the bug**
CrossfactionBG not working

**To Reproduce**
1. Compile OregonCore/Talamortis on Windows with CrossfactionBG module
2. Try entering  Battlegrounds with more than 8 mixed players.
3. The crossfactionBG is not activated

**Expected behavior**

**Module name**

mod_cfbg

**Comment by talamortis** [comment]
Did you re-run CMake after applying the module?

Did you apply the config?

**Comment by d3athbl0w** [comment]
Fixed on this commit: https://github.com/talamortis/OregonCore/commit/c7f46f1e34b5b31d323bc3cd68135801f5b70237

Thanks :)
